### ISSUE TITLE
rpp in documentation should be written as (TP+FP)/(P + N)

### ISSUE THREAD

**Issue by AndreMikulec** [ltorgo/performanceEstimation#4]
In 
man/classificationMetrics.Rd

"rpp" 
explanation text should be written as

``` text
given by  (TP+FP)/(P + N)
```

Instead of

``` text
given by (TP+FP)/N
```

of text

``` text
"rpp": rate of positive predictions, it is a metric  applicable to two classes
  tasks that measures the proportion of times the model
  forecasted a positive class, and it is
  given by (TP+FP)/N
```

**Comment by ltorgo** [comment]
Hi Andre,
Thanks for the noting this. Actually, the problem is related with the notation I'm using that needs to be changed because I'm using N for both the number of true negatives and the total number of test cases, and that leads to these confusions. I'll change this.
Thanks again,
Luis
