### ISSUE TITLE
true postive rate, senstivity, and recall: comma is in the wrong position

### ISSUE THREAD

**Issue by AndreMikulec** [ltorgo/performanceEstimation#5]
See the graph in the middle fo the page on the right side: 

``` text
The true-positive rate is also known as sensitivity, or recall in machine learning. That is O.K.

Receiver operating characteristic 
GRAPHIC in th middle of the page on the righ side: 
   TPR = TRUE_POSITIVE div_by CONDITION_POSITIVE
https://en.wikipedia.org/wiki/Receiver_operating_characteristic
```

In file: evaluationMetrics.R, 

``` r
# true positive rate =  sensitivity, or recall                       # COMMA is in the wrong position
r[c("tpr", "rec", "sens")] <- cm[posClass, posClass]/sum(cm[posClass, ]) 
```

Compared to the others # COMMA is in the correct position

``` r
r["fnr"]                   <- cm[posClass, negClass]/sum(cm[, posClass])
r["tnr"]                   <- cm[posClass, negClass]/sum(cm[, negClass])
```

Compared to false positive rate

``` r
# false positive rate
r["fpr"]                   <- cm[negClass, posClass]/sum(cm[, posClass])
```

A fix is needed.

``` r
# true plosive rate BEFORE FIX                                       # COMMA is in the wrong position
r[c("tpr", "rec", "sens")] <- cm[posClass, posClass]/sum(cm[posClass, ])

# true postie rate AFTER FIX ( TPR = TRUE_POSITIVE div_by CONDITION_POSITIVE )
# tpr: true positive rate                                            # COMMA is in the correct position
r[c("tpr", "rec", "sens")] <- cm[posClass, posClass]/sum(cm[, posClass]) 
```

Thanks,
Andre Mikulec
Andre_Mikulec@Hotmail.com

**Comment by ltorgo** [comment]
Hi Andre,
Thanks for the message, finding the bugs and sending a correction.
Actually, this was already found and corrected (in the development version) some time ago. My recommendation would be that you install and use the development version. It has several bug fixes and also some improved functionalities (like in parallelization). I will soon set this as the CRAN/official version but I'm waiting a bit more to eventually find other bugs and make some small changes, as well as some further testing.
Cheers,
Luis
